GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/1


###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Fred Firestones",
    "number": "100-22334455"
}
