GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Hello World",
    "author": "Gangplank",
    "url": "bussyslayer.com",
    "likes": 5
}

###
DELETE http://localhost:3003/api/blogs/63c4b11192065b94901f311b

###
PUT http://localhost:3003/api/blogs/63c4aecb18721de10cef7355
content-type: application/json

{
    "likes": 60
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "gigachad",
    "password": "magnumdong",
    "name": "chad"
}
